import React from 'react';
import type { UserProfile, JobApplication } from '../types';

interface CoverLetterTemplateProps {
  profile: UserProfile;
  app: JobApplication;
}

export function CoverLetterTemplate({ profile, app }: CoverLetterTemplateProps) {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Strip common markdown characters from cover letter body to make it look clean for print
  const cleanCoverLetter = (app.tailoredCoverLetter || '')
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/#/g, '');

  return (
    <div id="cover-letter-template" className="w-[816px] h-[1056px] bg-white p-16 text-slate-900 font-serif mx-auto box-border relative text-left flex flex-col justify-between">
      <div>
        <header className="mb-10 border-b border-slate-200 pb-6 font-sans">
          <h1 className="text-3xl font-bold uppercase tracking-tight text-slate-900 mb-1">{profile.name}</h1>
          <div className="flex gap-4 text-xs text-slate-500 font-medium">
            <span>{profile.email}</span>
            <span>•</span>
            <span>{profile.phone}</span>
            {profile.location && (
              <>
                <span>•</span>
                <span>{profile.location}</span>
              </>
            )}
          </div>
        </header>

        <div className="text-sm space-y-6 text-slate-800">
          <p className="font-medium font-sans text-slate-500">{today}</p>

          <div className="font-sans">
            <p className="font-semibold text-slate-900">Hiring Team</p>
            <p className="font-semibold text-indigo-600">{app.company}</p>
          </div>

          <div className="leading-relaxed whitespace-pre-wrap text-[14px] text-slate-800 font-serif space-y-4">
            {cleanCoverLetter || `Dear Hiring Team,\n\nI am writing to express my strong interest in the ${app.role} position at ${app.company}. Based on my background and skills, I am confident I would be a valuable addition to your team.\n\nSincerely,\n\n${profile.name}`}
          </div>
        </div>
      </div>
      
      <footer className="text-center text-[10px] text-slate-400 font-sans mt-auto pt-6 border-t border-slate-100">
        Generated by AutoJob AI Agent for {profile.name}
      </footer>
    </div>
  );
}
